openapi: 3.0.3
info:
  title: Example Orders API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8001
paths:
  /orders/{order_id}:
    get:
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            example: '123'
      responses:
        '200':
          description: Success
  /orders:
    post:
      requestBody:
        content:
          application/json:
            example:
              item: book
              quantity: 1
      responses:
        '201':
          description: Created
